FROM envoyproxy/envoy-dev:latest
COPY ./filters/hello-world/main.wasm /etc/filters/hello-world/main.wasm
COPY ./envoy.yaml /etc/envoy.yaml
RUN envsubst < /etc/envoy.yaml > /etc/envoy.yaml
RUN chmod go+r /etc/envoy.yaml
CMD ["/usr/local/bin/envoy", "-c", "/etc/envoy.yaml", "-l", "debug", "--service-cluster", "proxy"]
